post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: subl
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
