sources:
  - DynaPuff.glyphs
axisOrder:
  - wdth
  - wght
familyName: DynaPuff
#buildStatic: false
stat:
  DynaPuff[wdth,wght].ttf:
  - name: Width
    tag: wdth
    values:
    - name: Condensed
      value: 75
    - name: Normal
      value: 100
      flags: 2
  - name: Weight
    tag: wght
    values:
    - name: Regular
      value: 400
      linkedValue: 700
      flags: 2
    - name: Medium
      value: 500
    - name: SemiBold
      value: 600
    - name: Bold
      value: 700